version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - ./config:/opt/odoo/config
      - ./server:/opt/odoo/server
      - ./addons:/opt/odoo/addons
      - ./addons_extra:/opt/odoo/addons_extra
    restart: on-failure
volumes:
  db-data:
    driver: local
