# -*- coding: utf-8 -*-
{
    'name': 'Restaurant Installer',
    'version': '1.0.1',
    'category': 'Point of Sale',
    'sequence': 20,
    'summary': 'Restaurant',
    'description': """""",
    'depends': [
        # 'l10n_cu',
        # 'pos_garnish',
        # 'pos_restaurant_report',
        # 'pos_stock',
        # 'pos_restaurant_changes_control',
        # 'pos_restaurant_discounts_and_charges',
        # 'pos_restaurant_work_orders',
        # 'pos_cache',
        # 'pos_cash_control',
        # 'pos_thin_bill',
        # 'mrp',
        # 'purchase',
        # 'purchase_simplification',
    ],
    'data': [
        'data/pos_category_data.xml',
        'data/restaurant_table_data.xml',
        'data/uom_data.xml',
        'data/product_data.xml',
        'data/garnish_data.xml',
        'data/bom_data.xml',
        'data/company_data.xml',
        'data/pos_config_data.xml',
        'data/customer_data.xml',
        'data/supplier_data.xml',
    ],
    'demo': [],
    'test': [],
    'qweb':[],
    'website': '',
    'installable': True,
    'application': True,
    'auto_install': False,
}
